# Generated by Django 3.2.9 on 2021-11-06 18:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
