# Generated by Django 3.2.9 on 2022-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descrate',
            name='tasks_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='descrate',
            name='tasks_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
