# Generated by Django 3.2.9 on 2022-02-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20220228_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='descs',
        ),
        migrations.AddField(
            model_name='rate',
            name='descs',
            field=models.ManyToManyField(to='action.DescRate'),
        ),
    ]
