# Generated by Django 3.2.9 on 2021-11-06 19:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_alter_message_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
