# Generated by Django 3.2.9 on 2021-11-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20211111_1840'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rate',
            table='rate',
        ),
    ]
