# Generated by Django 3.2.9 on 2021-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_alter_rate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='first_af',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ar_dz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_be',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_bg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_br',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_bs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_cs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_cy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_da',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_dsb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_el',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_en_au',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_en_gb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_eo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_es_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_es_co',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_es_mx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_es_ni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_es_ve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_et',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_eu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_fi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_fy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_gd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_gl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_hr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_hsb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_hu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_hy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_io',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_is',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_kab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_km',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_kn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_lb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_lt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_lv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_mk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_mn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_mr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_nb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_nl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_nn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_pt_br',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sq',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sr_latn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_te',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_tg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_th',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_tk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_tt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_udm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_ur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='first_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_af',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ar_dz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_be',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_bg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_br',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_bs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_cs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_cy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_da',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_dsb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_el',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_en_au',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_en_gb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_eo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_es_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_es_co',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_es_mx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_es_ni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_es_ve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_et',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_eu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_fi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_fy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_gd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_gl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_hr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_hsb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_hu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_hy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_io',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_is',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_kab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_km',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_kn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_lb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_lt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_lv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_mk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_mn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_mr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_nb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_nl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_nn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_pt_br',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sq',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sr_latn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_te',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_tg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_th',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_tk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_tt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_udm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_ur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='second_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_af',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ar_dz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_be',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_bg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_br',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_bs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_cs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_cy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_da',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_dsb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_el',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_en_au',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_en_gb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_eo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_es_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_es_co',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_es_mx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_es_ni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_es_ve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_et',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_eu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_fi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_fy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_gd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_gl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_hr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_hsb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_hu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_hy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_io',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_is',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_kab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_km',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_kn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ko',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_lb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_lt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_lv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_mk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_mn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_mr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_nb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_nl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_nn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_pa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_pt_br',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sq',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sr_latn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_te',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_tg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_th',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_tk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_tt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_udm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_ur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='third_zh_hant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
