# Generated by Django 3.2.9 on 2021-12-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_auto_20211212_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='first_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='first_ru',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='first_uz',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='second_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='second_ru',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='second_uz',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='third_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='third_ru',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='third_uz',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='title_uz',
        ),
    ]
