# Generated by Django 3.2.9 on 2021-12-12 14:26

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0011_alter_message_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='phone_number_en',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='phone_number_uz',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
