# Generated by Django 3.2.9 on 2021-12-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_auto_20211212_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name_uz',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phone_number_uz',
            new_name='phone_number_ru',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='first_uz',
            new_name='first_ru',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='second_uz',
            new_name='second_ru',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='third_uz',
            new_name='third_ru',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='title_uz',
            new_name='title_ru',
        ),
    ]
