# Generated by Django 3.2.9 on 2021-12-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0014_auto_20211212_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name_en',
            new_name='name_uz',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phone_number_en',
            new_name='phone_number_uz',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='second_en',
            new_name='first_uz',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='first_en',
            new_name='second_uz',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='third_en',
            new_name='third_uz',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='title_en',
            new_name='title_uz',
        ),
    ]
