# Generated by Django 3.2.9 on 2022-02-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0016_auto_20220103_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name_tu',
        ),
        migrations.RemoveField(
            model_name='message',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='message',
            name='phone_number_tu',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='first_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='first_tu',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='second_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='second_tu',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='third_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='third_tu',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='title_tu',
        ),
    ]
